# Applicatie naam
spring.application.name=engie-bericht-api

# Server poort (Node mock draait al op 3000)
server.port=8080

# Loglevel
logging.level.com.engie=DEBUG

# Mooie JSON output
spring.jackson.serialization.indent-output=true

# Datum/tijd formaat in JSON
spring.jackson.serialization.write-dates-as-timestamps=false
